# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-01 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('companyAddress', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contactPersonName', models.CharField(blank=True, max_length=100, null=True)),
                ('contactPersonNo', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
