# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-05 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_email', models.EmailField(max_length=254)),
                ('contact_person_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('contactPerson', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('contactNo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_copy', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name_address_copy', models.CharField(blank=True, max_length=100, null=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_Address', models.TextField(blank=True, null=True)),
                ('contact_person_name_copy', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_email_copy', models.EmailField(max_length=254)),
                ('contact_person_no_copy', models.IntegerField(blank=True, null=True)),
                ('service_tax_rate', models.IntegerField()),
                ('Service_tax_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceParticulars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('period', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='particulars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invoice.InvoiceParticulars'),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invoice.CompanyCreation'),
        ),
    ]
