# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-01 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0002_registerclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(blank=True, max_length=100, null=True)),
                ('clientAddress', models.TextField(blank=True, null=True)),
                ('contactPerson', models.CharField(blank=True, max_length=100, null=True)),
                ('contactPersonNo', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('serviceTaxRate', models.IntegerField(blank=True, null=True)),
                ('serviceTaxAmount', models.IntegerField(blank=True, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
                ('clientName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Invoice.RegisterClient')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceParticulars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.TextField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('period', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='particulars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Invoice.InvoiceParticulars'),
        ),
    ]
