# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-01 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0004_auto_20160701_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='particulars',
        ),
    ]
