# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-02 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0006_invoiceparticulars_particulars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='clientContactPersonEmail',
            new_name='client_contact_person_email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='clientContactPersonName',
            new_name='client_contact_person_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='clientContactPersonNo',
            new_name='client_contact_person_no',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='invoiceName',
            new_name='invoice_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='termsAndConditions',
            new_name='terms_and_conditions',
        ),
        migrations.RenameField(
            model_name='companycreation',
            old_name='companyAddress',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='companycreation',
            old_name='companyName',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='companycreation',
            old_name='contactPersonName',
            new_name='contact_person_name',
        ),
        migrations.RenameField(
            model_name='companycreation',
            old_name='contactPersonNo',
            new_name='contact_person_no',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='clientAddresscopy',
            new_name='client_address_copy',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='contactPersonNamecopy',
            new_name='contact_person_name_copy',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='contactPersonNocopy',
            new_name='contact_person_no_copy',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='serviceTaxRate',
            new_name='service_tax_rate',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='termsAndConditionscopy',
            new_name='terms_and_conditions_copy',
        ),
        migrations.RenameField(
            model_name='invoiceparticulars',
            old_name='periodInDays',
            new_name='period_in_days',
        ),
    ]
