# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-06 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0008_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('statuspending', 'Status Pending'), ('sendtoclient', 'sendToclient'), ('cancelled', 'Cancelled'), ('amountreceived', 'Amount Received'), ('partialamountreceived', 'PartialAmountReceived')], default='statuspending', max_length=25),
        ),
    ]
